AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Max: 60
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 50
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/**'